plugins {
    id 'java-library'
    id 'application'
}

java {
    sourceCompatibility JavaVersion.VERSION_18
    targetCompatibility JavaVersion.VERSION_18
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.brott.dev/' }
    maven { url = 'https://jitpack.io' }
}

dependencies {
    implementation 'com.acmerobotics.roadrunner:MeepMeep:0.1.7'
}
application {
    mainClass = 'com.example.meepmeeptesting.MeepMeepTesting'
}

