plugins {
    id 'java-library'
    id 'application'
}

java {
    sourceCompatibility JavaVersion.VERSION_18
    targetCompatibility JavaVersion.VERSION_18
}

repositories {
    maven { url = 'https://jitpack.io' }
    maven {

        url = 'https://maven.brott.dev/'

    }
}

dependencies {
    implementation 'com.github.rh-robotics:MeepMeep:-SNAPSHOT'
}

application {
    mainClass = 'com.example.meepmeeptesting.MeepMeepTesting'
}

